# Project information
site_name: DevOps Notes 🦅
site_url: https://deependujha.github.io/DevOpsNotes
site_author: Deependu Jha
site_description: >-
  Collection of codes and concepts for quick reference.
# Repository
repo_name: deependujha/DevOpsNotes
repo_url: https://github.com/deependujha/DevOpsNotes

# Copyright
copyright: Copyright &copy; 2024-2025 Deependu Jha

extra_css:
  - stylesheets/my-style.css

# Configuration
theme:
  name: material
  features:
    # - announce.dismiss
    # - content.action.edit
    # - content.action.view
    # - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections # comment this if you want `navigation expansion and collapse`
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: images/assets/binary-code.png
  logo: images/assets/binary-code.png

# Additional configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/deependujha
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/deependu__
    - icon: fontawesome/brands/telegram
      link: https://t.me/deependu_jha

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

# Page tree
nav:
  - Home: index.md
  - Docker:
    - Home: 01-docker/index.md
  - Kubernetes:
      - Home: 02-kubernetes/index.md
  - AWS:
      - Home: 03-aws/index.md
  - GCP:
      - Home: 04-gcp/index.md
  - Kafka:
    - Home: 05-kafka/index.md
